### ISSUE TITLE
Support subresource integrity

### ISSUE THREAD

**Issue by jonathanstanley** [jfortunato/esbuild-plugin-manifest#11]
I haven't seen any discussion on this, but is there any interest in having this plugin support [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to improve security?

For example, with Webpack, [this plugin enables integrity hashes](https://github.com/webdeveric/webpack-assets-manifest#integrity), and also lets you [define which hashes to support](https://github.com/webdeveric/webpack-assets-manifest#integrityhashes).

**Comment by marcospereira** [comment]
Hey @jonathanstanley, I'm not sure if this is still relevant to you, but I've created #25 to address this issue and other things too.

**Comment by jfortunato** [comment]
I've included an example in the [README](https://github.com/jfortunato/esbuild-plugin-manifest?tab=readme-ov-file#subresource-integrity) that shows how this can be done using the `generate` option.
