### ISSUE TITLE
Plugin throwing unnecessary error when build result has errors

### ISSUE THREAD

**Issue by eddiemf** [jfortunato/esbuild-plugin-manifest#12]
When a build result contains errors it also doesn't include the `metafile` object in it, which makes the plugin throw an `Expected metafile, but it does not exist.` error. 

This is quite annoying because every time there's a mistake in code in watch mode it pollutes the entire console with this error, instead of showing only the actual code error.

I think a simple solution would be to simply return early if `result.errors.length` is truthy, and then if there are no errors but still `metafile` is missing we can throw that error. 

After such change it shows only the code error as expected.

**Comment by jfortunato** [comment]
Thanks for reporting @eddiemf. Starting with v0.6.0 this should be fixed now.
