### ISSUE TITLE
Incomplete manifest when using append with watch

### ISSUE THREAD

**Issue by ryanb** [jfortunato/esbuild-plugin-manifest#28]
I have several esbuild calls and I append the results into a single manifest.json using the `append: true` option. This works great when esbuild isn't watching the files. However when watch mode is enabled the builds happen in parallel causing them to all read the existing manifest at the same time and then attempt to write to it. The writes happen in a lock, but because it was read outside of the lock the resulting manifest is incomplete.

Is there a way to expand the lock so it includes the read/append behavior? This way the manifest is only read and appended to synchronously.

Thanks for making this plugin!

**Comment by jfortunato** [comment]
Thanks for reporting @ryanb. I'm hoping I've fixed this in `v1.0.5`. Give that release a try and see if that improves the append/watch compatibility for you. We can re-open this issue if things have not improved.

**Comment by ryanb** [comment]
@jfortunato seems to work great, thanks! I appreciate your work on this.
