### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by noahehall** [jfortunato/esbuild-plugin-manifest#5]
trying to install esbuild-plugin-manifest with next to 12.0.4

throws error
```js
ERESOLVE unable to resolve dependency tree
Found: esbuild@0.12.4
Could not resolve dependency:
peer esbuild@"^0.11.19" from esbuild-plugin-manifest@0.4
```

workaround: **using npm i -D .... --force**

everything appears to be working, is there a reason we limited to 0.11?

**Comment by jfortunato** [comment]
@noahehall Could you try installing again? v0.4.3 should fix the issue.

**Comment by noahehall** [comment]
w00p w00p !

@jfortunato thx man!
