### ISSUE TITLE
TypeScript types missing

### ISSUE THREAD

**Issue by sheepsteak** [jfortunato/esbuild-plugin-manifest#6]
Just thought I'd let you know that the `lib/index.d.ts` doesn't seem to get published with the code.

It looks like because `lib` is in the `.gitignore`, Yarn doesn't include it but it _does_ include the `lib/index.js`.

I tried putting `files: ["lib"]` in the `package.json` to force it and got this result:

<img width="188" alt="image" src="https://user-images.githubusercontent.com/1379888/119882606-82db3a80-bf26-11eb-8097-8ff71235b06f.png">

**Comment by jfortunato** [comment]
@sheepsteak Good catch. This is fixed in v0.4.4
