### ISSUE TITLE
Plugin fails if outdir is true, but write false in esbuild options

### ISSUE THREAD

**Issue by Csszabi98** [jfortunato/esbuild-plugin-manifest#7]
The plugin throws an error about non exitent directory when outdir is set, but write is also in the esbuild options.

The plugin should factor in the directories not being created, or create them itself, or add the created manifest file to the BuildResult (most desired).

**Comment by jfortunato** [comment]
@Csszabi98 This should be fixed in v0.4.5. When using esbuilds `write=false` option, the manifest file will be added to the BuildResult via the `outputFiles` property.

**Comment by Csszabi98** [comment]
@jfortunato I tested it, and it is working as expected, thank you!
